### ISSUE TITLE
Limit order doesn't exist

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#295] opened 2021-09-15 00:06 UTC
1. Sent an order
2. Cancelled it when it was partially filled
3. Signed the transaction when it was fully filled, thus non-existent

Should we handle this and provide a better output? @albertchon 
![RestingOrder](https://user-images.githubusercontent.com/83584143/133349599-86689614-581a-4215-91ff-61ce682d3563.PNG)

**Comment by bangjelkoski** [comment] 2021-11-03 22:21
I can't reproduce this.

**Comment by achilleas-kal** [comment] 2021-11-05 12:19
I tried multiple times, I don't get the stacktrace but we should probably provide a better output here. That's the output I get when I try to cancel an order that has been filled.

![image](https://user-images.githubusercontent.com/83584143/140509030-7faaa5a9-a5a5-4421-a868-30d7d490af63.png)

**Comment by bangjelkoski** [comment] 2021-11-05 12:43
This is returned from the chain sir, we can't change that. We can, but we would have to do cases for every error that the BE throws and handle it gracefully with a proper message and I don't think that is something we should do right now.

Also, this happens when the order was filled/cancelled but streaming didn't work and it wasn't updated on the UI so you cancel a non-existing order. I'll close the issue and we can have better messages parsing system in the future.

**Closed by bangjelkoski** 2021-11-05 12:43 UTC
Labels: bug, cant-reproduce
