### ISSUE TITLE
Markets disappear

### ISSUE THREAD

**Issue by achilleas-kal** [InjectiveLabs/injective-dex#345] opened 2021-11-05 16:03 UTC
Community reported that markets don't show on the DEX sometimes, I actually experienced this yesterday on devnet but I thought it because you were redeploying. In my case happened with open orders as well in the Portfolio page @bangjelkoski 

![image](https://user-images.githubusercontent.com/83584143/140540909-bf96d0d9-290a-4102-b3f2-0870020e1fdc.png)

**Comment by achilleas-kal** [comment] 2021-11-06 10:12
I replicated this last night, if you leave the tab to injective.exchange open for a few hours and continue working on something else when you come back the markets have disappeared - at least until you refresh.

**Comment by achilleas-kal** [comment] 2021-11-18 14:11
Most likely related to the Chronos BE issue, will check again when we fix and update here

**Comment by bangjelkoski** [comment] 2021-11-18 19:05
Can't reproduce, for now, they should just refresh. Let's reopen if it's something commonly reported.

**Comment by achilleas-kal** [comment] 2021-11-19 16:55
Re-opening since we've had more occurrences

**Comment by bangjelkoski** [comment] 2021-11-29 22:51
I've added a potential fix for this, lets see if it happens again and we can reopen.

**Comment by albertchon** [comment] 2021-12-02 00:20
Happened again...

**Comment by bangjelkoski** [comment] 2021-12-14 00:00
This is resolved by adding NaN market summaries when there is a Chronos API issue and handling them on the UI.

**Closed by bangjelkoski** 2021-12-14 00:00 UTC
Labels: bug
